# Generated by Django 3.2.14 on 2022-08-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('St_name', models.CharField(default=0, max_length=30, null=True)),
                ('F_name', models.CharField(default=0, max_length=30, null=True)),
                ('DOB', models.CharField(default=0, max_length=10, null=True)),
                ('Gender', models.CharField(default=0, max_length=10, null=True)),
                ('B_Form', models.CharField(default=0, max_length=30, null=True)),
                ('St_Mobile', models.CharField(default=0, max_length=20, null=True)),
                ('F_Cnic', models.CharField(default=0, max_length=20, null=True)),
                ('F_Mobile', models.CharField(default=0, max_length=20, null=True)),
                ('DateOfAdmission', models.CharField(default=0, max_length=10, null=True)),
                ('Program', models.CharField(default=0, max_length=20, null=True)),
                ('Package', models.IntegerField(default=0, null=True)),
                ('First_Installment', models.IntegerField(default=0, null=True)),
                ('Matric_RollNo', models.CharField(default=0, max_length=10, null=True)),
                ('Matric_Marks', models.CharField(default=0, max_length=5, null=True)),
                ('Admisson_By', models.CharField(default=0, max_length=40, null=True)),
                ('Approached_By', models.CharField(default=0, max_length=40, null=True)),
                ('Entered_By', models.CharField(default=0, max_length=30, null=True)),
                ('Status', models.CharField(default=0, max_length=10, null=True)),
            ],
        ),
    ]
