# Generated by Django 3.2.14 on 2022-08-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AspireApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='Sr_No',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
